# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-25 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
