# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190827_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
